### ISSUE TITLE
get an error when i try to deploy my changes, sqitch Cannot find change in plan

### ISSUE THREAD

**Issue by pengfei-xue** [theory/sqitch#269]
get an error when i try to deploy my changes, sqitch Cannot find change in plan, but if i switch the plan in sqitch.plan, it can be deployed successfully.

version: sqitch (App::Sqitch) 0.9993
mac os 10.11

**Comment by theory** [comment]
Please show an example of the plan, and the command you're running.

**Comment by pengfei-xue** [comment]
<img width="972" alt="1f1c081c-7823-461e-9dad-5afe47a552b9" src="https://cloud.githubusercontent.com/assets/1533151/10599643/77ab5dc2-7736-11e5-9570-17c62f356cee.png">

the command i ran is `sqitch deploy -t mydatabase

**Comment by pengfei-xue** [comment]
i can deploy the changes if i switch plan's order

**Comment by theory** [comment]
Okay, you're not saying what change it can't find, but I suspect that you deployed to this database once before. Once you deploy, you must not change the order of changes in the plan. This is because the SHA-1 hash generated for each change is includes the SHA-1 hash of the change that came before it. This insures that a production database doesn't get screwed up by things being applied out-of-order. The way to deal with this when you're doing development is to `sqitch rebase` your database when you want to make changes to the plan. That will revert all your deployed changes, then deploy the changes as they currently appear in your plan. If you only want to revert to a certain point, you can use the `--to` option to  `rebase` to control that. See [the `deploy` docs](/theory/sqitch/blob/master/lib/sqitch-deploy.pod) for details.

**Comment by pengfei-xue** [comment]
ok, thank, i have rebased the db changes, thanks, it's caused by a merge conflict, i resolved the conflicts, but changed the order of the plan. so, if there's a best practice for such situation? how to avoid this kind of error?

**Comment by theory** [comment]
You can see an example dealing with merge conflict resolution in the tutorials:

* [Introduction to Sqitch on PostgreSQL](lib/sqitchtutorial.pod)
* [Introduction to Sqitch on SQLite](lib/sqitchtutorial-sqlite.pod)
* [Introduction to Sqitch on Oracle](lib/sqitchtutorial-oracle.pod)
* [Introduction to Sqitch on MySQL](lib/sqitchtutorial-mysql.pod)
* [Introduction to Sqitch on Firebird](lib/sqitchtutorial-firebird.pod)
* [Introduction to Sqitch on Vertica](lib/sqitchtutorial-vertica.pod)
