### ISSUE TITLE
Altering Table with "rework"

### ISSUE THREAD

**Issue by dacodekid** [theory/sqitch#282]
I've tried several times to follow the 'postgres tutorial', just except instead of altering a function, I'm changing a field name in table. But it ends up with same error.

```
╰─$ sqitch verify
Verifying sqtest_db
  * appschema .... ok
  * contact ...... ok
Undeployed change:
  * contact
Verify successful
╭─dacodekid@mbp  ~/dev/sqtest
╰─$ sqitch deploy
Deploying changes to sqtest_db
  + contact .. psql:deploy/contact.sql:10: ERROR:  relation "contact" already exists
not ok
"/usr/local/bin/psql" unexpectedly returned exit value 3

Deploy failed
```

This is my before `tagged` and after `tagged` deploy query

BEFORE
```sql
BEGIN;
CREATE TABLE sq_schema.contact
  (
    log_date DATE NOT NULL,
    emp_name CHARACTER VARYING(100) DEFAULT ''
  );
COMMIT;
```

AFTER
```sql
BEGIN;

CREATE TABLE sq_schema.contact
  (
    log_date DATE NOT NULL,
    employee_name CHARACTER VARYING(100) DEFAULT ''
  );

COMMIT;
```

**Comment by theory** [comment]
Rework is intended for making [idempotent](https://en.wikipedia.org/wiki/Idempotence) changes, such as `CREATE OR REPLACE FUNCTION`. The `CREATE TABLE` statement is not idempotent. If you want to add a column to a table, I suggest either:

1. If you have not released your database, just modify the `CREATE TABLE` statement in the original change and `sqitch rebase` to revert all changes and redeploy with the updated table. This is ideal when doing development.

2. Otherwise, add a new change, named `$table_$column` or some such, and use an [`ALTER TABLE`](http://www.postgresql.org/docs/current/static/sql-altertable.html) statement to add the new column. This is the approach to take if you have released the database already, though you can also do it before release if you like.

If you have any more questions, the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) is the best place to post them. Hope to see you there!

**Comment by dacodekid** [comment]
@theory, `ALTER TABLE` makes sense. I asked it in [SO](http://stackoverflow.com/questions/35086596/altering-table-with-sqitch-rework-command), but will use mail list from now on. Appreciate it.

**Comment by theory** [comment]
Right, thanks for the SO pointer. I posted the answer there, too.

**Comment by winduptoy** [comment]
@theory Thank you so much for all of this. I too had this question after reading the tutorial. Might be useful to specifically call this out.
