### ISSUE TITLE
Add Dependency To Change After Starting Work

### ISSUE THREAD

**Issue by davidkuep** [theory/sqitch#285]
Not sure quite where to ask this, but I've run into the issue that when I create a change using sqitch add  and then when deploying or testing said change I realize I've forgotten a dependency. Is there a way to add a dependency that I'm missing? Right now I have to go in and reset the git repository, delete all the files by hand etc. I've tried just updating the dependencies in sqitch.plan but it doesn't seem to work, though it seems like it should. Am I missing something there?

**Comment by theory** [comment]
Yeah, you should be able to just add the dependency to the plan (and to the comments in the deploy file, if you like, though Sqitch doesn't read those), and then rebase the change. You won't be able to deploy unless you rebase (or revert and deploy, which amounts to the same thing), because the SHA ID will have changed with the addition of the dependency. But otherwise it should just work.

You might be interested in signing up for the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) to post questions in the future. :-)
