### ISSUE TITLE
sqitch deploy to pg database ignores -h option

### ISSUE THREAD

**Issue by Bill** [theory/sqitch#293]
I want to deploy to a database on a PostgreSQL server running in a Docker container at dockerhost.local. Of course this:

```
$ sqitch deploy db:pg:flipr_test
could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

Because the socket doesn't exist. But this:

```
$ sqitch -h dockerhost.local deploy db:pg:flipr_test
```

Gives the same `No such file or directory` error.

What gives? Does `sqitch deploy` not support -h for the PostgreSQL driver?

**Comment by theory** [comment]
It should put it in, so this might be a bug. However, this should work:

    sqitch deploy db:pg://dockerhost.local/flipr_test

**Comment by Bill** [comment]
Thanks for the quick response! Better:

```
Bills-MacBook-Pro:flipr bill$ sqitch deploy db:pg://dockerhost.local/flipr_test
FATAL:  role "bill" does not exist
Bills-MacBook-Pro:flipr bill$ sqitch -u postgres deploy db:pg://dockerhost.local/flipr_test
FATAL:  role "bill" does not exist
```

Looks like -u is ignored too. But this kinda works:

```
Bills-MacBook-Pro:flipr bill$ sqitch deploy db:pg://dockerhost.local/flipr_test?user=postgres
Adding registry tables to db:pg://dockerhost.local/flipr_test?user=postgres
psql: FATAL:  role "bill" does not exist
"/usr/local/bin/psql" unexpectedly returned exit value 2
```

**Comment by theory** [comment]
sqitch deploy db:pg://postgres@dockerhost.local/flipr_test

**Comment by Bill** [comment]
Perfect. Thanks! (I had already gotten it to work as the "bill" user by adding a login role w/ that name and doing `GRANT ALL ON DATABASE flipr_test TO bill;`) But this works now:

```
$ sqitch revert db:pg://postgres@dockerhost.local/flipr_test
Revert all changes from db:pg://postgres@dockerhost.local/flipr_test? [Yes] 
  - appschema .. ok
$ sqitch deploy db:pg://postgres@dockerhost.local/flipr_test
Deploying changes to db:pg://postgres@dockerhost.local/flipr_test
  + appschema .. ok
```

I suppose lack of `-u` support for deploy to pg is still a bug but I'm out of the woods now.

**Comment by theory** [comment]
Oh, I see what's going on with the ignoring of `-h`. Sqitch assumes that if you use a URI target, that it's complete, and ignores the `-h` and other database options. So if I run

    sqitch -h localhost status config

It ends up with the URI `db:pg://localhost/configuration`. But if I specify a URI:

    sqitch -h localhost status db:pg:configuration

It ignores the `-h`, using `db:pg:configuration`. This is because, if you're using a URI, you can explicitly list the host in the URI:

    sqitch status db:pg://localhost/configuration

No need for the `-h`. This is also a reflection of the fact that the `-h` and other database options have been informally deprecated since target URIs were introduced, though I've been hesitant to actually remove them, since so many people use them, and they can be useful for just replacing small parts of target URIs.

Anyway, not a bug, it works as intended. Will give some thought as to whether that's dumb or not.
