### ISSUE TITLE
"Cannot find deploy template"

### ISSUE THREAD

**Issue by SheriefAlaa** [theory/sqitch#310]
```
vagrant@vagrant-ubuntu-trusty-64:~/code/ALEX/sqitch$ sqitch add categories_order_array -n "Adds a categories_order_array field in user_roles table."
Use of uninitialized value $name in concatenation (.) or string at /usr/local/share/perl/5.18.2/App/Sqitch/Command/add.pm line 144.
Use of uninitialized value $name in concatenation (.) or string at /usr/local/share/perl/5.18.2/App/Sqitch/Command/add.pm line 144.
Use of uninitialized value $name in concatenation (.) or string at /usr/local/share/perl/5.18.2/App/Sqitch/Command/add.pm line 144.
Cannot find deploy template
vagrant@vagrant-ubuntu-trusty-64:~/code/ALEX/sqitch$ 
```

Any help would be appreciated. Thanks.

**Comment by theory** [comment]
What's the output of `sqitch engine`?

**Comment by SheriefAlaa** [comment]
```
What's the output of sqitch engine?
```

```
mysql
```

**Comment by theory** [comment]
I'm not able to replicate that:

    > md tmp
    > cd tmp/ 
    > sqitch init --engine mysql foo                                  
    Created sqitch.conf
    Created sqitch.plan
    Created deploy/
    Created revert/
    Created verify/
    > sqitch add categories_order_array -n "Adds a categories_order_array field in user_roles table."      
    Created deploy/categories_order_array.sql
    Created revert/categories_order_array.sql
    Created verify/categories_order_array.sql
    Added "categories_order_array" to sqitch.plan

What version of Sqitch are you using?

**Comment by SheriefAlaa** [comment]
```
vagrant@vagrant-ubuntu-trusty-64:~/code/ALEX/sqitch$ sqitch --version
sqitch (App::Sqitch) 0.9995
```

**Comment by austinried** [comment]
I recently encountered this same issue and found the solution, which may be the same in your case.  We're using windows with vagrant VMs as well, but with centos, and I had initialized a project inside vagrant.  I was able to add/deploy/everything just fine, but a co-worker who pulled the newest changes down could not and got the same error here.

Turned out that sqitch is [looking for templates](http://search.cpan.org/~dwheeler/App-Sqitch-0.9995/lib/sqitch-add.pod#Templates) by trying to grab the template name from the engine of the target, not finding that, and then not initializing the value of $name and failing.

What took me forever to track down was that when my co-worker had pulled down the project, git was set to checkout files with **CRLF line endings, not LF.**  This seems to cause the add command to silently fail to read or not read correctly the **sqitch.conf** file in the project directory, and then fail when it can't find the template name.  Once the line endings were changed to CRLF, the add command worked as expected. I ended up adding the line `*.conf eol=lf` to our `.gitattributes` file to prevent that from happening in the future.

So @theory, you should be able to duplicate this by changing the line endings in sqitch.conf to CRLF.

**Comment by theory** [comment]
Nice catch, @austinried, thanks!

**Comment by theory** [comment]
Replicated the issue, submitted bestpractical/config-gitlike#13 with failing tests demonstrating the issue. Note that #338 dupes this issue. Anyway, will hopefully be fixed when Config::GitLike learns how to better handle foreign line endings.

**Comment by jpSimkins** [comment]
I am having this exact same issue on sqitch (App::Sqitch) 0.9996
