### ISSUE TITLE
[Proposal] Allow sql files to be generated by an executable script

### ISSUE THREAD

**Issue by docteurklein** [theory/sqitch#323]
The idea would be to allow dynamic generation of some deploy (or verify/revert) scripts if the file is executable.

By using a shebang, one would be able to write any sql to STDOUT in any language, thus allowing very powerful manipulations.

I hope you see what I mean. If not, I can try to clarify with an example.

If you find it useful I can try to make a PR.

Cheers!

**Comment by Ovid** [comment]
I've desperately needed this myself, particularly with MySQL and needing to use the Percona tools to allow live db migrations on large systems. What you can do is this:

```
sqitch config --user core.mysql.client /path/to/my/script
```

Now, instead of mysql being called with your migrations, `/path/to/my/script` is called instead. It's not documented well, so you'll need to play around with it a bit, but it's worked wonders for me.

**Comment by docteurklein** [comment]
@Ovid ho that's an intersesting approach indeed. I need to figure out exactly what the script receives as arguments / options / stdin, but that would definitely solve the problem. Thanks for the hint!

A native solution might still be interesting tho.

**Comment by theory** [comment]
Duplicates #1.

**Comment by docteurklein** [comment]
oops, sorry! I tried to find an existing one, but didn't find this one.
