### ISSUE TITLE
How to correct object name

### ISSUE THREAD

**Issue by k3n** [theory/sqitch#339]
I have a function, let's say it's named `foo`, and some time ago we created a change for it, but inadvertently named the change `bar`.

So now, obviously, we have a file named `bar.sql` but which refers to function `foo`.

I would like to correct the file to be `foo.sql`, but simply renaming the file is easy. I could plausibly manually update `sqitch.plan` as well, but I have no idea what the implications of that would be. I'm also aware that sqitch stores data in the DB that contains these names as well.

Is there an easy way to fix this snafu? I apologize if I missed it in the docs, if it's there.

**Comment by theory** [comment]
If you have never deployed, and don't mind rebuilding your database, yes, you can just rename the scripts and change the name in the plan file. Don't forget to change the name in any places that reference the old name as a dependency! I do this all the time. My shell history is full of commands like this:

    for dir in deploy revert test verify; do git mv $dir/bar.sql $dir/foo.sql; done

If you have existing databases, you'll need to revert before you make these changes, because otherwise it won't be able to find the revert script:

    sqitch revert --to bar^

If, however, you've deployed to a production database, or for any other reason you can't revert changes our just drop your databases, I'm afraid you're stuck with the name. This is because Sqitch uses SHA-1 hashes to identify each change, and the hashes include the names of the changes as well as the SHA-1 of the previous change! So renaming things would change the hashes and Sqitch would be unable to find them in your databases.

**Comment by theory** [comment]
Also, check out the [mail list](https://groups.google.com/forum/#!forum/sqitch-users). It's the ideal place for questions like this. In fact, there was a similar question [just yesterday](https://groups.google.com/forum/#!topic/sqitch-users/TARQosN7h04).

**Comment by k3n** [comment]
Dang, ok. Thanks!
