### ISSUE TITLE
Question: how do you keep an overview as a developer?

### ISSUE THREAD

**Issue by twentyfortytwenty** [theory/sqitch#368]
Hello all,

We are doing an analysis on how sqitch could be useful for the database migrations in our company. We have several (500+) databases of the same project in the wild and it is getting difficult to keep track of their current scheme version for each instance. Unfortunately, not all customers are running the latest version of the project. Upgrading to a later/the latest version is therefore always tricky and sqitch would be the ideal solution for that problem wrt. the database. But our developers (myself included) raised a question wrt. development.

Let me try to explain. We start with a script which creates a table. I did not include the revert and verify scripts, as I believe they are not relevant to the question.

```
BEGIN;
CREATE TABLE sometable (
    identifier UUID PRIMARY KEY,
    ....
    somecolumn TEXT NOT NULL,
    ....
);
COMMIT;
```

Then, we realize that the column `somecolumn` should be nullable. So we create a second script which does this:

```
BEGIN;
ALTER TABLE sometable ALTER somecolumn SET NULL;
COMMIT;
```

Although this works and our devops/admins are loving this (as all they have to do is `sqitch deploy` which will run all necessary scripts in the desired order depending on the current state of the target database), the concern from the developers team is that you will end up with a lot of scattered scripts and that it will be difficult to keep overview on the current/latest version of the database scheme. In the flow above, there is no script which basically holds **the latest and complete version of the database scheme**. The developer has either to go over all scripts and try to follow, or either execute `sqitch deploy` against a dummy database to find out the **scheme as of today**.

In addition to creating the second script, our developers would love to **also** update the first script (replace `NOT NULL` by `NULL`). This way, they can always open the first script to see the latest and complete version of the database scheme as of today. When doing a `sqitch deploy` against a certain database, sqitch will be smart enough whether to execute the first script or the second script.

Is this kind of flow possible in sqitch?

Thank you!

**Comment by wesselvdv** [comment]
I believe the [rework option](https://github.com/theory/sqitch/blob/master/lib/sqitch-rework.pod) is useful for this type of situation? I have yet to try it, but the fact that Sqitch has such an option was a deciding factor for me to start using it in my own team. 

I do hope that I have interpreted the functionality correctly, but how I envision using Sqitch is that every (relevant) entity inside the DB has one file that is always the most current version, and that it could have multiple 'older' revisions in the form of reworked files. From what I understood, when utilising this, Sqitch is smart enough to only deploy the 'current' version and ignore the reworked ones when deploying on a fresh DB. Much how you're describing your preferred flow.

**Comment by theory** [comment]
No, this is not possible. Well, not for tables. The [rework command](https://github.com/theory/sqitch/blob/master/lib/sqitch-rework.pod) provides this functionality for objects that can be replaced idempotently. Examples include `CREATE OR REPLACE FUNCTION` and `CREATE OR REPLACE VIEW` in Postgres. But for `CREATE TABLE`, it makes no sense. So what usually happens is one of two things:

1. Subsequent changes are made by new changes (`sqitch add`) with `ALTER TABLE` commands, as in your example, @twentyfortytwenty. This is the typical pattern.
2. Subsequent changes are made by reworked changes (`sqitch rework`), but still with `ALTER TABLE` commands, since, as you might guess, you can't replace a table without dropping all the data in it. Some folks prefer this pattern because then all the changes for an object are more closely associated, with the latest change in the original deployment script, and older changes in adjacent scripts with `@tagname` appended to them.

But if what you want is some record of the final form of a table, that's best handled by dumping the schema for that table, which your preferred database engine should be able to do for you.

HTH!

PS: I have *got* to find a better way to make clear that there is a [mail list](https://groups.google.com/forum/#!forum/sqitch-users) that's ideal for questions like this; the [current site](http://sqitch.org/) doesn't make it obvious to people.

**Comment by theory** [comment]
@wesselvdv Sqitch does not deploy only the latest reworked script, because it could mess with dependencies. For example if you had a change that created table foo with column bar, then one that created table yaz that references bar, but then you later drop bar, well, it could get complicated. So Sqitch always deploys previous versions in the order in the plan in which they were supposed to have been created, and applies reworked versions as appropriate as it works through the plan.

**Comment by twentyfortytwenty** [comment]
@theory Thank you for your response! It's all clear for us now. We understand the specifics now. Unfortunately, this means that we are not going to integrate sqitch into our work flow, as our developers really want to maintain the latest/current database scheme (and of course, migration SQL scripts which reflect these changes for a live database).

So as an example, we prefer having a single `customers.sql` for all customer related entities (tables, views, functions, triggers, ...) which always holds the latest version.

Thanks for tuning in @theory and @wesselvdv, appreciated!

**Comment by theory** [comment]
Yeah, sorry, that's likely a different tool.
