### ISSUE TITLE
Re-use connection for each migration

### ISSUE THREAD

**Issue by joeandaverde** [theory/sqitch#382]
Currently, it seems that sqitch establishes a new connection for each migration that's run. We have about 250 migrations and establishing a remote SSL connection is very slow.

Is it feasible to keep the already established connection?

**Comment by theory** [comment]
Sqitch uses a single connection for its registry tasks, but since the design specifically targets the engine-native command-line clients (`psql`, `mysql`, etc.), it can only pass one script at a time. If you could convince your engine's client to re-use a connection between executions, that's be the way to go. But personally I've found the ability to control other apps quite limited.
