### ISSUE TITLE
Add documentation on using pg_tap with sqitch

### ISSUE THREAD

**Issue by joevandyk** [theory/sqitch#78]
What's the best way of using pg_tap with sqitch? 

I wouldn't want to add pg_tap to production databases, I think (so that rules out adding a 'deploy' script for pg_tap).

Should the pg_tap extension be installed on test databases outside of sqitch? Or maybe the pg_tap extension is installed by a verification script if it doesn't exist yet?

**Comment by petru-ghita** [comment]
@theory could you please elaborate why it is a bad idea to use pgTAP for the verify/*.sql ? (extraordinary tools both of them, and big thank you for open source them!).  Also, as it seems related, why wouldn't you want pgTAP on a production database?

If I modify the template and add yet another directory to the existing deploy, verify and revert would that get properly versioned and stored with the rest of the pack? I'm mainly concerned by the rework operation.

Thank you!

**Comment by theory** [comment]
Yeah, you can add other directories to the Sqitch template. I've used it at work for some common but non-trivial changes (probably should move them to an app, but time is only so free).

I personally don't like the idea of pgTAP in prod because I don't like _anything_ in prod other than what's required to run a service (or database). Every extra unnecessary thing expands the attack surface. If a vulnerability were to be found in pgTAP, I wouldn't want it hanging out in prod where someone could use it.

That said, I may be overly security-paranoid here. After all, Aurora and RDS Postgres both make pgTAP available with a single call to `CREATE EXTENSION pgtap`. Perhaps if the user the connects to the database for your app does not have permission to install extensions, but the user you use for deployments does, you could put `CREATE EXTENSION pgtap` at the top of your verify scripts and let it be rolled back at the end.
